export const MILISECONDS_PER_SECONDS = 1000;
export const SECONDS_PER_MINUTE = 60;
export const MINUTE_PER_HOUR = 60;
export const HOUR_PER_DAY = 24;
export const DAY_PER_MONTH = 30;
export const DAY_PER_WEEK = 7;

export const ACCESS_TOKEN_EXPIRY =
  15 * SECONDS_PER_MINUTE * MILISECONDS_PER_SECONDS;

export const REFRESH_TOKEN_EXPIRY =
  DAY_PER_WEEK *
  HOUR_PER_DAY *
  MINUTE_PER_HOUR *
  SECONDS_PER_MINUTE *
  MILISECONDS_PER_SECONDS;
